promotion_link:
    - wall-126196970_47871 # добавить в беседу
    - wall-126196970_46581 # Список ботов с главной
    - wall-126196970_55040 # CRR

weather200: [
    "за окном хорошо так громыхает!",
    "Тор вовсю разбушевался",
    "Небеса разверзлись! Бойтесь, грешники!"
]
weather201: [
    "за окном гремит да еще и дождь хлещет",
    "Славьте великого Одина, пока он нас не покарал",
    "Пиздец, в общем."
]
weather202: [
    "не, из дома реально не вариант выходить",
    "Всё очень плохо",
    "В такую погоду нормальные люди дома сидят, телевизор смотрят.\nТолько чужие шастают."
]
weather210: [
    "у нас тут гроза а у вас?",
    "Просто гроза, ничего особенного. Листайте дальше.",
    "Так себе гроза, бледненькая"
]
weather211: [
    "а вы знаете, что звук грозы доходит позже чем свет от нее?",
    "Мы настоятельно не рекомендуем вам стоять на крыше с арматурой, поднятой вверх.",
    "Громыхает как в аду, якорь мне в жопу!"
]
weather212: [
    "от грома стекла вылетают",
    "Нет, ну это совсем пиздец. Кто за ущерб платить будет?\nПерун?"
]
weather221: ["в гугл транслейте перевелось как рваная граза хз что это?"]
weather230: ["гроза с ледышками"]
weather231: ["погода реально хуевая"]
weather232: ["пиздец, как при такой погоде жить то вообще а?"]
weather300: [
    "чутка подморосило",
    "Если выйти на улицу, поднять лицо кверху и открыть рот, то можно прийти к выводу, что это дождь.",
    "Чуточку мокро, брррр"
]
weather301: [
    "на улице моросит как телки при виде Стаса Михайлова",
    "Такой дождь как раз под кабачки хорошо"
]
weather302: [
    "почти что дождь",
    "Дождём вас не смоет, но на ходу лучше не эсемесить"
]
weather310: ["различают 56 видов дождя. Этот - 14-й."]
weather311: ["Вроде как дождь идет, а вроде и нет"]
weather312: ["Пиздец, дождь так дождь"]
weather313: [
    "Очень холодный дождь!",
    "Брррррррр!"
]
weather314: ["На улице мокрый и ледяной ад, не ходи туда"]
weather321: ["Тебе понадобится защитный костюм из Советской армии!"]
weather500: [
    "Грибной дождик",
    "Когда дождь закончится, хватай лукошко и пиздуй по грибы!",
    "Чучуточку мокро, но жить можно."
]
weather501: ["Дождь еще не определился - идет он или нет"]
weather502: ["Неплохо так поливает!"]
weather503: ["Пиздец там льет как из ведра!"]
weather504: ["ЕБАНЫЙ ПОТОП СУКА, НАШУ ПОГОДНУЮ СТАНЦИЮ ЗАЛИВАЕТ, ААААА!"]
weather511: ["Мало того, что дождь так еще и холодно"]
weather520: ["Ливень ебашит."]
weather521: ["Хороший такой ливень!"]
weather522: ["ЕБАНЫЙ ЛИВЕНЬ!"]
weather531: ["В тебя подливень попал!"]
weather600: ["Снег вроде бы как есть, но в снежки не поиграть!"]
weather601: ["Снег мокрый как твоя маман при виде Филиппа Киркорова"]
weather602: ["Метель хуярит, ничего не видно отсюда."]
weather611: ["Добро пожаловать в Санкт-Петербург! Да, тут всегда так."]
weather612: ["Бля, это короче и снег и вода одновременно!"]
weather615: ["Дождь хуярит, снег идет"]
weather616: ["На улице очень грязно, прямо как в России"]
weather620: ["Пойдем лепить снеговика!"]
weather621: ["Снежный аппокалипсис!!!"]
weather622: ["Я не верю, что бывает столько снега!"]
weather701: ["Противотуманные фары включи, если есть!"]
weather711: ["ВЕЙПЕРЫ ЕБАНЫЕ ВСЕ НАКУРИЛИ ТУТ!"]
weather721: ["Не видно нихуя!"]
weather731: ["БЛЯТЬ ТУТ ПЕЩАНАЯ БУРЯ!"]
weather741: ["Ебаный туман!"]
weather751: ["ПЫЛЕВАЯ БУРЯ, ЕБАТЬ!"]
weather761: ["de_dust2"]
weather762: ["ЕБУЧЕЕ БЛЯТЬ ИЗВЕРЖЕНИЕ МАТЬ ЕГО ВУЛКАНА!"]
weather771: ["СДУВАЕТ НАХЕР! ПАМАГИТЕ!"]
weather781: ["БЛЯТЬ УРАГАН! СУКА, ДА КАК ЖЕ ТАК?"]
weather800: [
    "Ясно как божий день",
    "Хороша погода, иди гулять",
    "Облаков не видать",
    "Заебись погода 👍",
    "Красота, на небе ни облачка"
]
weather801: [
    "На небе есть облачко похожее на Сало",
    "Есть облака, но чучуточку",
    "Кажется, дождь собирается",
    "Что-то там в небе чёрненькое белеется"
]
weather802: [
    "Я прогулял на уроках географии урок про облака, не могу перевести это.",
    "Возмущения в верхних слоях атмосферы, бла-бла-бла ...",
    "Жди непогоды",
    "Я бы при таком раскладе гулять не ходил"
]
weather803: [
    "МНОГА ОБЛАКОВ",
    "Заебись тучи",
    "А вот и тучки подъехали",
    "Пасмурно, тоскливо и безысходно"
]
weather804: [
    "ТУЧИ ХОДЯТ",
    "Тучи какие-то непостоянные",
    "Облака туда-сюда шастают, хз."
]
weather900: ["там Торнадо? Ты че в пиндостане?"]
weather901: ["ЕБУЧИЙ ТРОПИЧЕСКИЙ ШТОРМ"]
weather902: ["Ураган степени Катрина!"]
weather903: ["ПИЗДЕЦ ХОЛОДНО"]
weather904: ["АХУЕТЬ, ЖАРКО КАК В АДУ!"]
weather905: ["ВЕТЕР УНОСИТ ЛУЧШИХ ИЗ НАС!!!!"]
weather906: ["Град размером с арбуз. Не завидую автовладельцам без гаража!"]
weather951: ["Штиль.. Ветер молчит.."]
weather952: ["епта! такого мы точно не ожидали!"]
weather953: ["Погода я думаю хрошая!"]
weather954: ["Зачем смотреть погоду в Боте?"]
weather955: ["Бриз хуярит!"]
weather956: ["Ветрюга!"]
weather957: ["Буря!"]
weather958: ["Буран!"]
weather959: ["Хуярит ветер блять!"]
weather960: ["Ебать, здесь написано шторм, ты че, в море?"]
weather961: ["Пиздец, шторм ебашит, утром СМС от МЧСников пришла"]
weather962: ["ЕБАТЬ-КОЛОТИТЬ, УРАГАН!"]


speechmaker0: [
    "Уважаемые коллеги! ",
    "Здравствуйте!",
    "Здравствуйте товарищи! ",
    "Здравствуйте уважаемые коллеги! ",
    "Приветсвую вас, коллеги! ",
    "Дамы и господа, прошу внимания. ",
    "Здравствуйте уважаемые дамы и господа! ",
    "Здравствуйте уважаемые товарищи! ",
    "Прошу минуточку внимания. "
]


speechmaker1: [
    "Товарищи! ",
    "С другой стороны, ",
    "Равным образом, ",
    "Не следует, однако, забывать что ",
    "Таким образом, ",
    "Повседневная практика показывает, что ",
    "Значимость этих проблем настолько очевидна, что ",
    "Разнообразный и богатый опыт доказывает - ",
    "Задача организации, в особенности же ",
    "Идейные соображения высшего порядка, а также "
]

speechmaker2: [
    "реализация намеченных плановых заданий ",
    "рамки и место обучения кадров ",
    "постоянный количественный рост и сфера нашей активности ",
    "сложившаяся структура организации ",
    "новая модель организационной деятельности ",
    "дальнейшее развитие различных форм деятельности ",
    "постоянное информационно-пропагандистское обеспечение нашей деятельности ",
    "укрепление и развитие структуры ",
    "консультация с широким активом ",
    "начало повседневной работы по формированию позиции "
]

speechmaker3: [
    "играет важную роль в формировании ",
    "требуют от нас анализа ",
    "требуют определения и уточнения ",
    "способствует подготовке и реализации ",
    "обеспечивает широкому кругу специалистов участие в формировании ",
    "позволяет выполнить важные задания по разработке ",
    "в значительной степени обусловливает создание ",
    "позволяет оценить значение ",
    "представляет собой интересный эксперимент проверки ",
    "влечет за собой процесс внедрения и модернизации "
]

speechmaker4: [
    "дальнейших направлений развития. ",
    "системы массового участия. ",
    "существующих финансовых и административных условий. ",
    "позиций, занимаемых участниками в отношении поставленных задач. ",
    "новых предложений. ",
    "направлений прогрессивного развития. ",
    "системы обучения кадров, соответствующей насущным потребностям. ",
    "соответствующих условий активизации. ",
    "модели развития. ",
    "форм воздействия. "
]

speechmaker5: [
    "С уважением, ваш бот проекта Платформа Сало Интеллект. ",
    "С уважением, ваш Бот.",
    "Искренне ваш, мемас с пикабу.",
    "Искренне ваш, Бот.",
    "Искренне ваш, Бот серии \"Сало Интеллект\"",
    "Спасибо за внимание.",
    "Спасибо за внимание, всем до скорых встреч и досвидания. "
]

telegram_inline_st: "cmd st"
telegram_inline_help: "help"
telegram_inline_time: "cmd time"
telegram_inline_me: "cmd me"
telegram_inline_botstats: "cmd botstats"
telegram_inline_photo: "cmd get photo"
telegram_inline_music: "cmd get music"