additions:
  - {mode: insert, path: fetcher_keyword, value: bot}
  - {mode: insert, path: fetcher_keyword, value: бот}
  - {mode: insert, path: primary_keyword, value: bot}
  - {mode: insert, path: primary_keyword, value: бот}
  - {mode: set, path: available/history, value: false}

  # Enable database editing commands
  - { mode: set, path: cmd/all/db_add/active,    value: yes }
  - { mode: set, path: cmd/all/db_remove/active, value: yes }
  
  # Commercial help head
  - { mode: set, path: 'cmd/all/help_main/command',  value: cmd get_config_text --list help/contact_link_commercial help/main  }
  - { mode: set, path: 'cmd/all/help_beta/command',  value: cmd get_config_text --list help/contact_link_commercial help/beta  }
  - { mode: set, path: 'cmd/all/help_admin/command', value: cmd get_config_text --list help/contact_link_commercial help/admin }
  
  - mode: set
    path: bot_name
    value: commercial25
  - mode: set
    path: bot_name_public
    value: Яша
  - mode: insert
    path: fetcher_keyword
    value: яша
  - mode: insert
    path: primary_keyword
    value: яша
  - mode: insert
    path: fetcher_keyword
    value: павший
  - mode: insert
    path: primary_keyword
    value: павший
  - mode: set
    path: media_text/help/contact_link_commercial
    value: 
        "Разговорный чат-бот на платформе \"Сало Интеллект\". \n\
        SaloIntellect (с) \n\
        by muxamed666 and DDRDmakar \n\
        Об обнаруженных ошибках сообщайте администратору.\n\
        Группа Яши ВКонтакте https://vk.com/club161419686\n\
        Создатель Яши\nhttps://vk.com/id357230628\n\
        "
