# HELP

# help head
help_contact_link:
"Разговорный чат-бот на платформе \"Сало Интеллект\". \n\
 \n\
SaloIntellect (с) \n\
by muxamed666 and DDRDmakar \n\
Бот запущен группой ...\n\
"
# for usual users
help_main:
"=========================== \n\
Справка пользователя \n\
=========================== \n\
help / info / помощь / инфо / хелп - эта справка \n\
=========================== \n\
> > > Команды \n\
📊 нагрузка - статистика по сообщениям \n\
🎨 картинка - кинуть картинку \n\
📢 музыка - кинуть музыку \n\
🎬 видео - кинуть видео \n\
▪ гиф   - кинуть гифку \n\
⏳ время - текущие время и дата сервера \n\
✏ напиши <...> - Сделать большую надпись символами \n\
👾 зови меня <...> - Поменять имя (обращение бота к вам) \n\
👓 ник <...> - генерировать ник из необычных символов \n\
💵 оцени <...> - даёт оценку (можно картинку) \n\
🇷🇺 транслит <...> - транслитерация текста \n\
💌 послание <...> - отправить послание \n\
💾 обучение - обучать бота \n\
. конец обучения - закончить обучение \n\
📌 виселица - игра \"угадай слово\" \n\
📌 города - игра в \"города\" \n\
💾 включить шрифт <0/1/2/3/4/5/6> \n\
. . . изменить шрифт бота \n\
. . . 0 - обычный \n\
. . . 1 - быдлотранслит \n\
. . . 2,3 - верхний и нижний регистр \n\
. . . 4 - мудрённые буквы \n\
. . . 5 - классич. транслит \n\
. . . 6 - иероглифы \n\
▪ cmd random <begin> <end> - рандомное число из заданного диапазона \n\
📊 cmd st - состояние сервера \n\
📊 cmd botstats - статистика сообщений этого бота \n\
▪ help2 - Дополнительные команды \n\
▪ ahelp - Команды администратора \n\
=========================== \n\
> > > Специальные возможности: \n\
▪ <математический пример> - калькулятор \n\
▪ <число> - разбор числа \n\
▪ <...или...или...> - выбор из нескольких вариантов \n\
▪ скажи / повтори <...> - повторение фразы \n\
▪ вероятность / инфа <...> - определение вероятности (%) \n\
▪ что такое <...> - информация из википедии \n\
=========================== \n\
"

# for admins
help_admin: No admin help here

# additional help
help_beta:
"> > > Дополнительные команды: \n\
▪ аниме - картиночки с анимешными няшами. \n\
▪ пони - картинки с пони ( MLP ) \n\
▪ ссср - для юных революционеров \n\
▪ сша - для любителей капитализма \n\
▪ прон - 🌚🌚 ну вы поняли \n\
▪ ваще похуй - портрет Грэма \n\
▪ посоветуй фильм/сериал/книгу \n\
▪ факт - расскажет интересный факт \n\
▪ анекдот - расскажет анекдот \n\
▪ цитата - цитаты великих и не очень людей \n\
"

# help for teachers
help_teacher:
"РЕЖИМ ОБУЧЕНИЯ \n\
Бот будет присылать сообщения, вам нужно будет вписывать ответы на них. \n\
Если сообщение не нужно сохранять, то напишите \"del\" или просто \"П\", чтобы пропустить его. \n\
Чтобы выйти из режима обучения, напишите \"Стоп обучение\" или \"Конец обучения\". \n\
Просьба не называть конкретных личностей и без причины не использовать оскорбления в ответе. Ответы должны быть универсальны. \n\
Сохранённые ответы будут через некоторое время добавлены в общую базу. \n\
Спасибо за содействие, вы реально очень помогаете! \n\
======================"

# ban tips
ban_help: No ban help here
