high_scores:
  max_n_messages:
    n_messages: 8615
    id: maryana_networking_vkgroup_490749035
    name: Ольга Тупицына
  teachmode:
    max_teachmessages:
      n_messages: 742
      id: maryana_networking_vkgroup_260714273
      name: Артур Мурадян