### COEFFICIENT
random_num:        50  ### От нуля до какого числа выбираются рандомные номера, Включительно
random_num_pow:    2   ### на 10 от нулевой до какой степени это число умножаетсяВключительно

query_limit_small: 12   # Максимальное число записей в малой выборке из базы
query_limit_norm:  600  # в средней выборке
query_limit_big:   6000 # В большой выборке

flood_mes_count:     7 ### Кол-во одинаковых сообщений до бана. Нестрогое неравенство.
flood_mes_count_pre: 4 ### Кол-во одинаковых сообщений до предупреждения. Нестрогое неравенство.
ban_time:            1   ### Количество часов в бане за флуд

### LIMITS
### Неравенства нестрогие, включительно, то есть значение, стоящее на конце, находится в разрешённом диапазоне

len_max_single_unknown_word:    4 # Максимальная длина одного непонятного короткого слова. На него отвечает смайлом
len_min_words_del_short_words:  5 # Минимальное количество слов, при котором можно удалять короткие слова
len_min_remove_word:            3 # Во сколько раз строка должна быть длиннее слова, чтобы его удалить

len_min_part_message_query:       144  # Минимальная длина, при которой конвеер пропускает запрос с полным текстом сообщения
len_min_words_part_message_query: 144  # Минимальное количество слов, при котором конвеер пропускает запрос с полным текстом сообщения
len_min_repeat_control:           10   # Минимальная длина сообщения, при которой бот может ругаться на поаторения пользователя
len_min_word_in_pair:             4    # Минимальная длина слова в паре при разбиении слов на пары
len_max_delete_short_words:       2    # Максимальная длина короткого слова, которое можно удалять
len_max_unsolved_little_message:  12   # Максимальная длина сообщения, которое можно запоминать как нераспозаннное
len_max_spam_message:             4000 # Сколько максимально может быть символов сгенерировано командой cmd spam

len_max_mes:         3456 ### Включительно. Максимальная длина отправляемого сообщения
len_max_big_text:    14   ### Включительно.
len_max_username:    36   ### Включительно.
len_max_description_query:  1000 ### Включительно. Максимальная длина запроса к википедии (в байтах)

max_count_dynamic_operation_user:    3456 # Сколько максимально может быть участников в динамическом списке участников (например, обучение)
max_len_detect_smile:         7           # Максимальная длина сообщения, при которой можно распознавать самйлы в тексте
max_len_database_string:      256         # Максимальная длина строки, которую можно записать в базу
max_count_capsule_messages:   24          # Максимальное количество сообщений в списке посланий

random_year_beg:        2017 # Начальный год диапазона рандомных дат
random_year_end:        2019 # Конечный год
