# HELP

# help head
# Шапка, идущая вместе со всеми справками help
help_contact_link:
"Разговорный чат-бот на платформе \"Сало Интеллект\". \n\
SaloIntellect (с) \n\
by muxamed666 and DDRDmakar \n\
Об обнаруженных ошибках сообщайте администратору.\
"


# for usual users
# Общая справка help, для всех
help_main:
"=========================== \n\
Справка пользователя \n\
=========================== \n\
help / info / помощь / инфо / хелп - эта справка \n\
=========================== \n\
> > > Команды \n\
📊 нагрузка - статистика по сообщениям \n\
🎨 картинка - кинуть картинку \n\
🎧 музыка - кинуть музыку \n\
🎬 видео - кинуть видео \n\
💻 гиф   - кинуть гифку \n\
📢 скажи - перевести текст в звук \n\
🎨 зеркало + картинка - отзеркалить фото \n\
🎨 редактор - редактор изображений \n\
⏳ время - текущие время и дата сервера \n\
✏ напиши <...> - Сделать большую надпись символами \n\
👾 зови меня <...> - Поменять имя (обращение бота к вам) \n\
👓 ник <...> - генерировать ник из необычных символов \n\
💵 оцени <...> - даёт оценку (можно картинку) \n\
🇷🇺 транслит <...> - транслитерация текста \n\
💌 послание <...> - отправить послание \n\
💾 обучение - обучать бота \n\
. конец обучения - закончить обучение \n\
💽 добавить [фраза] [ответ] - Добавить ответ. Квадратные скобки нужны \n\
💽 удалить <ответ> - Удалить ответ бота. Треугольные скобки не нужны \n\
📌 виселица - игра \"угадай слово\" \n\
📌 города - игра в \"города\" \n\
🎤 мужской/женский голос - включить режим голосовых ответов \n\
. выключить голос - выйти из режима голосовых ответов \n\
💾 включить шрифт <0/1/2/3/4/5/6> \n\
. . . изменить шрифт бота \n\
. . . 0 - обычный \n\
. . . 1 - быдлотранслит \n\
. . . 2,3 - верхний и нижний регистр \n\
. . . 4 - мудрённые буквы \n\
. . . 5 - классич. транслит \n\
. . . 6 - иероглифы \n\
🎲 cmd random <begin> <end> - рандомное число из заданного диапазона \n\
📊 cmd st - состояние сервера \n\
📊 cmd botstats - статистика сообщений этого бота \n\
⚠ help2 - Дополнительные команды \n\
⚠ ahelp - Команды администратора \n\
⛔ reset - выйти из всех режимов \n\
=========================== \n\
> > > Специальные возможности: \n\
📟 <математический пример> - калькулятор \n\
📝 <число> - разбор числа \n\
📋 <...или...или...> - выбор из нескольких вариантов \n\
⚡ скажи / повтори <...> - повторение фразы \n\
✔️ вероятность / инфа <...> - определение вероятности (%) \n\
🔎 что такое <...> - информация из википедии \n\
💦 погода <город> - узнать погоду \n\
=========================== \n\
"

# for admins
# Справка для админов и разработчиков (status: [0,1])
# Здесь все команды бота в их изначальном виде.
help_admin:
" \n\
* - for admins only \n\
** - for creators only \n\
~ - argument is not necessary \n\
( id = botname + \"_\" + interface + \"_\" + userID ) \n\
 \n\
CONSOLE \n\
▪ st - display status of the server \n\
▪ loadstatus - not present in Salo 2, will be deleted soon \n\
▪ *statistics - display statistics of the server \n\
▪ msgstats - display statistics of messages \n\
▪ timings - show session uptime and time before session restart \n\
▪ *fulltimings - not present in Salo 2, will be deleted soon \n\
▪ botstats - bot's messages statistics \n\
▪ speechmal <text> \n\
▪ speechfem <text> \n\
▪ weather <place> \n\
▪ syncbans - synchronize ban-lists \n\
▪ repost <post id> \n\
▪ pinrepost <post id> \n\
CONVEER \n\
▪ *cmd attachment_list \n\
▪ cmd me \n\
▪ cmd random \n\
▪ cmd time \n\
▪ cmd banme \n\
▪ cmd complain \n\
▪ cmd get <type> <~type_sub> \n\
▪ cmd get_config_media <address> \n\
▪ *cmd add_attachment <bot_interface_type> <~type_sub> <link> \n\
▪ *cmd remove_attachment <link> \n\
▪ **cmd changeuserstatus <id> <status> \n\
▪ *cmd teachmode <on/off> \n\
▪ *cmd ban <id> <n_hours> <~reason> \n\
▪ *cmd unban <id> \n\
▪ *cmd answer_db  \n\
- - > add [phrase] [answer] \n\
- - > remove [<phrase>] [<answer>] \n\
- - > remove <answer> \n\
- - > look <answer> \n\
▪ cmd help main/*admin/beta \n\
▪ cmd random <begin> <end> \n\
▪ cmd write <text> \n\
▪ cmd say <text> \n\
▪ cmd callme <text> \n\
▪ cmd fetch <type> <~type_sub> \n\
▪ cmd description <text> \n\
▪ cmd fancytext <text> \n\
▪ cmd capsule <text> \n\
▪ cmd translit <text> \n\
▪ cmd encode <text> \n\
▪ cmd sponsor ... ( move to console ) \n\
▪ cmd play <game_guess_word/game_word_chain/stop> \n\
▪ cmd changeleet <num> \n\
▪ cmd id \n\
▪ cmd image ... \n\
▪ cmd image -preset \"preset_name\" -parameter_name value \n\
▪ cmd add admin \"user id\" - make user admin \n\
▪ cmd add admin \"user id\" ++ - make user superadmin \n\
▪ cmd delete admin \"user id\" - delete user from admins \n\
▪ cmd reset - reset all modes \n\
"

# additional help
# Дополнительная справка help, в ней менее важные команды и особенности бота
help_beta:
"> > > Дополнительные команды: \n\
▪ аниме - картиночки с анимешными няшами. \n\
▪ пони - картинки с пони ( MLP ) \n\
▪ ссср - для юных революционеров \n\
▪ сша - для любителей капитализма \n\
▪ прон - 🌚🌚 ну вы поняли \n\
▪ ваще похуй - портрет Грэма \n\
▪ посоветуй фильм/сериал/книгу \n\
▪ факт - расскажет интересный факт \n\
▪ анекдот - расскажет анекдот \n\
▪ цитата - цитаты великих и не очень людей \n\
▪ 666 - цитата из библии Сатаны \n\
"

# help for teachers
# Справка для обучающих бота
help_teacher:
"РЕЖИМ ОБУЧЕНИЯ \n\
Бот будет присылать сообщения, вам нужно будет вписывать ответы на них. \n\
Если сообщение не нужно сохранять, то напишите \"del\" или просто \"П\", чтобы пропустить его. \n\
Чтобы выйти из режима обучения, напишите \"Стоп обучение\" или \"Конец обучения\". \n\
Просьба не называть конкретных личностей и без причины не использовать оскорбления в ответе. Ответы должны быть универсальны. \n\
Сохранённые ответы будут через некоторое время добавлены в общую базу. \n\
Спасибо за содействие, вы реально очень помогаете! \n\
======================"

# ban tips
# Подсказки к команде "ban"
ban_help:
"Command form:\ncmd ban botname_interface_userid n_hours [reason] \n\
cmd ban _networking_vkcom_ 00 \n\
cmd ban salo_networking_vkcom_8 100500 Оскорбления \n\
cmd ban bogdan_networking_vkcom_5 100500 Реклама \n\
...\n\
"
