### GAMES
# Ответ, что игра прервана
game_stop: Игра прервана.
# Ответ, что пользователь не находится в игровом режиме
game_error_not_participant:    Ошибка - вы не находитесь в игровом режиме. Выключение всех игровых параметров.
# Ответ, что пользователь уже находится в игровом режиме
game_error_double_participant: Ошибка - вы уже находитесь в игровом режиме.

### Game guess word
# Приветствие
game_guess_word_intro: "ИГРА \"Угадай слово\"\nДля выхода из игры напишите \"конец игры\" или \"стоп игра\".\n========"
game_guess_word_win:   Вы выиграли !!!   # Ответ, что пользователь выиграл
game_guess_word_lose:  'Вы проиграли :с' # Ответ, что пользователь проиграл
game_guess_word_current_word: 'Слово:'   # Слово: ...
game_guess_word_letters:  'Букв:'        # Букв: ...
game_guess_word_mistakes: 'Ошибок:'      # Ошибок: ...
game_guess_word_used_letters: 'Использованные буквы:' # Использованные буквы: ...
# Текст, завершающий игровое сообщение
game_guess_word_additional:   "Назовите букву \nИли же рискните отгадать слово целиком!"
# Ответ, что введены некорректные аргументы
game_guess_word_incorrect_input:  "(игровой режим)\nОшибка - некорректные входные данные. Попробуйте снова.\nЧтобы завершить игру, напишите \"стоп игра\"."
# Ответ, что введённая буква уже была использована
game_guess_word_repeating_letter: Вы уже использовали эту букву.
# Ответ-ошибка, что пользователь не является игроком
game_guess_word_nousr:    Error - user is not a player
# Ответ-ошибка, что в базе данных игры не найдено слов
game_guess_word_empty_db: Error - empty gallows database
# Ответ-ошибка, что введённая пользователем строка пуста
game_guess_word_noword:   Error - empty input word in game-guess-word
# Максимальное число ошибок до проигрыша
max_game_guess_word_mistakes: 9

### Game word chain
# Приветствие
game_word_chain_intro:    "ИГРА \"Города\"\nИмя каждого следующего города должно начинаться на последнюю букву имени предыдущего. Если имя города оканчивается на Ь, Ъ или Ы, то игрок использует предпоследнюю букву.\nДля выхода из игры напишите \"конец игры\" или \"стоп игра\".\n========"
game_word_chain_myword:   'Я выбираю город:' # Я выбираю город: ...
# Ответ-ошибка, что введены некорректные данные
game_word_chain_incorrect_input: "(игровой режим)\nОшибка - некорректные входные данные. Попробуйте снова.\nЧтобы завершить игру, напишите \"стоп игра\"."
# Ответ, что введённый город уже был использован в игре
game_word_chain_word_used: Этот город уже был использован, попробуйте другой.
# Ответ, что пользователь выиграл
game_word_chain_win:      "Вы выиграли!!!\nБот в замешательстве, он больше не знает городов на эту букву."
game_word_chain_score:    'Вы набрали очков:' # Вы набрали очков: ...
game_word_chain_nousr:    Error - user is not a player # Ответ-ошибка, что пользователь не является игроком
game_word_chain_empty_db: Error - empty word-chain database # Ответ-ошибка, что в базе данных игры не найдено слов
game_word_chain_noword:   Error - empty input word in game-word-chain # Ответ-ошибка, что введённая пользователем строка пуста
