### UTILITY

# Начала сообщения, на которые реагирует бот
fetcher_keyword:
    - "привет всем"
    - "всем привет"
    - "доброе утро"
    - "с добрым утром"
    - "добрый вечер"
    - "всем пока"
    - "спокойной ночи"
    - "доброй ночи"
    - "споки"

# Начала сообщения, которые бот отрезает
primary_keyword:
    - "бот"
    - "bot"
    - "боты"
    - "bots"

### Сюда добавить ботов ( интерфейс + _ + id )
# Список пользователей, которых платформа должна игнорировать
ignore_list:
    - networking_vkcom_307249355 # salo
    #- networking_vkcom_399969615 # bogdan
    - networking_vkcom_414440855 # shava
    #- networking_vkcom_415198261 # grib
    - networking_vkcom_417021564 # kim
    #- networking_vkcom_421472300 # boris
    - networking_vkcom_429676630 # maryana
    - networking_vkcom_440955069 # doshik
    - networking_vkcom_441128669 # grib 2

# Разрешённые типы вложения (для команды get)
valid_attachment_type: ["photo", "audio", "video", "document"]

# Разрешённые типы шрифта (для преобразователя стилей шрифта в конце конвеера)
valid_leet_type: ['0', '1', '2', '3', '4', '5', '6', '7', '8']

# Типы, которые бот может озвучивать голосом
message_form_with_speech_answer_available:
    - ''
    - repeat
    - choice
    - '?_reason'
    - person
    - x_count
    - time
    - where
    - opinion
    - boolean
    - info

# Интерфейсы бота, на которых возможно озвучивание текста голосом
interface_with_speech_answer_available:
    - networking_vkcom
    - networking_vkgroup

# Типы сообщений, при которых запрещено преобразовывать стиль текста
message_form_change_text_style_forbidden:
    - command
    - help
    - ban_flood
    
### Типы, при определении которых с вложением конвеер не ищет части сообщения по базе.
non_parsable_type: ["evaluate", "choice"]
### Типы, при определении которых с вложением конвеер не будет искать ответ в истории.
attachment_depending_type: ["boolean", "likelihood", "evaluate", "choice", "?_reason", "person", "x_count",
"time", "where", "opinion"]

### Типы, при которых ответ не ищется по тстории (без вложения и с вложением)
type_dont_dig_history: ["number"]
type_dont_dig_history_with_attachment: ["boolean", "likelihood", "evaluate", "choice", "?_reason", "person", "x_count", "time", "where", "opinion", "number"]
### Типы, при которых ответ не ищется до определения типа (без вложения и с вложением)
type_dont_parse_before_typecheck: ["number"]
type_dont_parse_before_typecheck_with_attachment: ["number", "evaluate", "choice"]

# Статусы пользователей, которые могут добавлять в базу запрещённые фразы
answer_db_add_forbidden_words_rights: [0,1,3]

# Строки, предшествующие сообщению, которые конвеер должен отрезать перед анализом текста
primary_symbol: ["/"]

# Список используемых баз данных MySQL
all_databases: ["SALODATABASE", "GRIBDATABASE", "ANIMEBOT", "MARYANA"]

### Символы, которые не должны быть "склеены" в слове с обычными символами
strange_symbol: ["0123456789", "😍😘😗😙😚🤗😻👫👬👭💑👩‍❤‍👩👨‍❤‍👨💏👩‍❤‍💋‍👩👨‍❤‍💋‍👨💋🌹🌷🌼💐💍🍸☕🏩💒🎈🎀🎁💌❤💛💙💚💜💔❣💕💞💓💗💖💘💝💟😀😬😁😂😃😄😅😆😇😉😊🙂🙃☺😋😌😍😘😗😙😚😜😝😛🤑🤓😎🤗😏😶😐😑😒🙄🤔😳😞😟😠😡😔😕🙁☹😣😖😫😩😤😮😱😨😰😯😦😧😢😥😪😓😭😵😲🤐😷🤒🤕😴💤💩😈👿👹👺💀👻👽🤖😺😸😹😻😼😽🙀😿😾🙌👏👋👍👎👊✊✌👌✋💪🙏☝👆👇👈👉🖕🤘🖖✍💅👄👅👂👃👁👀👤🗣👶👦👧👨👩👱👴👵👲👳👮👷💂🕵🎅👼👸👰🚶🏃💃👯👫👬👭🙇💁🙅🙆🙋🙎🙍💇💆💑👩‍❤‍👩👨‍❤‍👨💏👩‍❤‍💋‍👩👨‍❤‍💋‍👨👪👨‍👩‍👧👨‍👩‍👧‍👦👨‍👩‍👦‍👦👨‍👩‍👧‍👧👩‍👩‍👦👩‍👩‍👧👩‍👩‍👧‍👦👩‍👩‍👦‍👦👩‍👩‍👧‍👧👨‍👨‍👦👨‍👨‍👧👨‍👨‍👧‍👦👨‍👨‍👦‍👦👨‍👨‍👧‍👧👚👕👖👔👗👙👘💄💋👣👠👡👢👞👟👒🎩⛑🎓👑🎒👝👛👜💼👓🕶💍🌂👦🏻👧🏻👨🏻👩🏻👴🏻👵🏻👶🏻👱🏻👮🏻👲🏻👳🏻👷🏻👸🏻💂🏻🎅🏻👼🏻💆🏻💇🏻👰🏻🙍🏻🙎🏻🙅🏻🙆🏻💁🏻🙋🏻🙇🏻🙌🏻🙏🏻🚶🏻🏃🏻💃🏻💪🏻👈🏻👉🏻☝🏻👆🏻🖕🏻👇🏻✌🏻🖖🏻🤘🏻🖐🏻✊🏻✋🏻👊🏻👌🏻👍🏻👎🏻👋🏻👏🏻👐🏻✍🏻💅🏻👂🏻👃🏻🚣🏻🛀🏻🏄🏻🏇🏻🏊🏻🚴🏻🚵🏻🐶🐱🐭🐹🐰🐻🐼🐨🐯🦁🐮🐷🐽🐸🐙🐵🙈🙉🙊🐒🐔🐧🐦🐤🐣🐥🐺🐗🐴🦄🐝🐛🐌🐞🐜🕷🦂🦀🐍🐢🐠🐟🐡🐬🐳🐋🐊🐆🐅🐃🐂🐄🐪🐫🐘🐐🐏🐑🐎🐖🐀🐁🐓🦃🕊🐕🐩🐈🐇🐿🐾🐉🐲🌵🎄🌲🌳🌴🌱🌿☘🍀🎍🎋🍃🍂🍁🌾🌺🌻🌹🌷🌼🌸💐🍄🌰🎃🐚🕸🌎🌍🌏🌕🌖🌗🌘🌑🌒🌓🌔🌚🌝🌛🌜🌞🌙⭐🌟💫✨☄☀🌤⛅🌥🌦☁🌧⛈🌩⚡🔥💥❄🌨⛄☃🌬💨🌪🌫☂☔💧💦🌊🍏🍎🍐🍊🍋🍌🍉🍇🍓🍈🍒🍑🍍🍅🍆🌶🌽🍠🍯🍞🧀🍗🍖🍤🍳🍔🍟🌭🍕🍝🌮🌯🍜🍲🍥🍣🍱🍛🍙🍚🍘🍢🍡🍧🍨🍦🍰🎂🍮🍬🍭🍫🍿🍩🍪🍺🍻🍷🍸🍹🍾🍶🍵☕🍼🍴🍽⚽🏀🏈⚾🎾🏐🏉🎱⛳🏌🏓🏸🏒🏑🏏🎿⛷🏂⛸🏹🎣🚣🏊🏄🛀⛹🏋🚴🚵🏇🕴🏆🎽🏅🎖🎗🏵🎫🎟🎭🎨🎪🎤🎧🎼🎹🎷🎺🎸🎻🎬🎮👾🎯🎲🎰🎳🚗🚕🚙🚌🚎🏎🚓🚑🚒🚐🚚🚛🚜🏍🚲🚨🚔🚍🚘🚖🚡🚠🚟🚃🚋🚝🚄🚅🚈🚞🚂🚆🚇🚊🚉🚁🛩✈🛫🛬⛵🛥🚤⛴🛳🚀🛰💺⚓🚧⛽🚏🚦🚥🏁🚢🎡🎢🎠🏗🌁🗼🏭⛲🎑⛰🏔🗻🌋🗾🏕⛺🏞🛣🛤🌅🌄🏜🏖🏝🌇🌆🏙🌃🌉🌌🌠🎇🎆🌈🏘🏰🏯🏟🗽🏠🏡🏚🏢🏬🏣🏤🏥🏦🏨🏪🏫🏩💒🏛⛪🕌🕍🕋⛩⌚📱📲💻⌨🖥🖨🖱🖲🕹🗜💽💾💿📀📼📷📸📹🎥📽🎞📞☎📟📠📺📻🎙🎚🎛⏱⏲⏰🕰⏳⌛📡🔋🔌💡🔦🕯🗑🛢💸💵💴💶💷💰💳💎⚖🔧🔨⚒🛠⛏🔩⚙⛓🔫💣🔪🗡⚔🛡🚬☠⚰⚱🏺🔮📿💈⚗🔭🔬🕳💊💉🌡🏷🔖🚽🚿🛁🔑🗝🛋🛌🛏🚪🛎🖼🗺⛱🗿🛍🎈🎏🎀🎁🎊🎉🎎🎐🎌🏮✉📩📨📧💌📮📪📫📬📭📦📯📥📤📜📃📑📊📈📉📄📅📆🗓📇🗃🗳🗄📋🗒📁📂🗂🗞📰📓📕📗📘📙📔📒📚📖🔗📎🖇✂📐📏📌📍🚩🏳🏴🔐🔒🔓🔏🖊🖋✒📝✏🖍🖌🔍🔎❤💛💙💚💜💔❣💕💞💓💗💖💘💝💟☮✝☪🕉☸✡🔯🕎☯☦🛐⛎♈♉♊♋♌♍♎♏♐♑♒♓🆔⚛🈳🈹☢☣📴📳🈶🈚🈸🈺🈷✴🆚🉑💮🉐㊙㊗🈴🈵🈲🅰🅱🆎🆑🅾🆘⛔📛🚫❌⭕💢♨🚷🚯🚳🚱🔞📵❗❕❓❔‼⁉💯🔅🔆🔱⚜〽⚠🚸🔰♻🈯💹❇✳❎✅💠🌀➿🌐Ⓜ🏧🈂🛂🛃🛄🛅♿🚭🚾🅿🚰🚹🚺🚼🚻🚮🎦📶🈁🆖🆗🆙🆒🆕🆓0⃣1⃣2⃣3⃣4⃣5⃣6⃣7⃣8⃣9⃣🔟🔢▶⏸⏯⏹⏺⏭⏮⏩⏪🔀🔁🔂◀🔼🔽⏫⏬➡⬅⬆⬇↗↘↙↖↕↔🔄↪↩⤴⤵#⃣*⃣ℹ🔤🔡🔠🔣🎵🎶〰➰✔🔃➕➖➗✖💲💱©®™🔚🔙🔛🔝🔜☑🔘⚪⚫🔴🔵🔸🔹🔶🔷🔺▪▫⬛⬜🔻◼◻◾◽🔲🔳🔈🔉🔊🔇📣📢🔔🔕🃏🀄♠♣♥♦🎴👁‍🗨💭🗯💬🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🕛🕜🕝🕞🕟🕠🕡🕢🕣🕤🕥🕦🕧🇦🇺🇦🇹🇧🇾🇧🇪🇧🇷🇨🇦🇨🇱🇨🇳🇨🇴🇩🇰🇫🇮🇫🇷🇩🇪🇭🇰🇮🇳🇮🇩🇮🇪🇮🇱🇮🇹🇯🇵🇰🇿🇲🇴🇲🇾🇲🇽🇳🇱🇳🇿🇳🇴🇵🇭🇵🇱🇵🇹🇵🇷🇷🇺🇸🇦🇸🇬🇿🇦🇰🇷🇪🇸🇸🇪🇨🇭🇹🇷🇺🇦🇦🇪🇬🇧🇺🇸🇻🇳"]

# Список названий промежутков времени
date_names: ["минут", "часов", "дней", "недель", "месяцев", "лет"]
# Текст, предшествующий выбору какого-то варианта
option_prefix: [":", "Думаю, что:", "Пожалуй, выберу:", "Я выбираю:", "Вариант:", "Однозначно:"]
