### *regex_number_real ((\+|-)?[[:digit:]]+)(\.(([[:digit:]]+)?))?
### *regex_number_int  (\+|-)?[[:digit:]]+

### *regex_keyword_who .*(кто |хто ).*

regex_game_word_chain_restricted_letters: '[ъЪьЬыЫ]$'

### "full" means that it should match the whole phrase
### "part" means that it should match any part of the phrase

regex_full_single_integer: (([0-9]+)|(0b[01]+)|(0x[0-9a-fA-F]+))

# regex_part_web_link: ([0-9a-zA-Zа-яА-ЯёЁ_]+\.(com|ru|org|net|ml|рф|tv|tk|info|biz|lv|cz|de|in|us|ua|kz|su|pw|name|tm))

regex:
    full:
        # Сначала то, что соответствует полной строке, а потом то, что соответствует части строки
        forbidden_teachmode_phrases: "(шлюха|дура|сука|шкура|сосунок|(по)?соси мне|шмара|да|не\\)*|нет\\)*|что.?|\
            с[оа]си.?|ага|ясн[о]?|понятно|ок|угу|всмысле.?|[\\(\\)]+|прост.?|ды+\\)*|неа|\
            хуй тебе|ничего|хуй|и ч(то|е|ё)|бля|\\?|что.|м{1,8}|так|как|ну (ок|да))|привет|\
            ([\\w\\W]*(\
            мамк|маман|нах[уо]й|нахер|умри|[сз]дохни|[её]баный|\
            (иди|пошла|пош[её]л) в пизду|я тебя люблю|пиздуй|у[её]бывай|\
            подп[еи]шись|подпишешься|гандон|подписка|накрут|(поставь|го) лайк|на аву|вступи|вступай|репост|\
            (групп(а|у|е)|пабл|страни|сообщ)|в друзья|\
            id[\\d]+|деньги|денег|заработа(й|ть)|(ищешь|не можешь найти) работу|(заходи|зайди) на |создатель|\
            плюну|в рожу|(ты|ленивая) (жопа|задница)|по[- ]русски|тебе.+рот|маленький|короткий|\
            отсталый|еблан|хуйло|хуило|сосни.+(хуй|хуец)|ебанько|пид[ао]?р|вы.+пидоры|коза|\
            отсоси|пососи|сосни|соснул|мой хуй|вонючка|(по?ш[её]л|по?шла|иди) (нах|в пизду)|изо рта|хуй.+во рту|\
            вы все|все вы|урод(ина)?|те.+ в рот|иди |иди нах|пидр|дурак|хуй те|мудак|шакал|ты [сз]дох|\
            с[ао]си |пош([её]л|ла) ты|отстань|suck my|\
            нич(е|ё|его)|ни(где|кого|как|сколько)|\
            режим|обучени|teachmode|you.*banned|не (пон(я|има|e|и)|пойму)|голосов|вы?ключи(ть)?\
            )[\\w\\W]*)"
        forbidden_command: # REGEX команд, запрещённых для каждой из групп пользователей
            0: '[^\w\W]'
            1: '[^\w\W]'
            2: 'cmd get_config_text --list help/contact_link help/admin'
            3: '[^\w\W]'
    part:
        forbidden_answer: ((накрутк|подпи(ск|ш)|www|https?|id\d+).+)|([0-9a-zA-Zа-яА-ЯёЁ_]+\.[a-zA-Zа-яА-ЯёЁ_]{1,8})|(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})|([0-9a-fA-F]{1,4}(\:{1,2}[0-9a-fA-F]{0,4}){2,8})
        
